### ISSUE TITLE
Dont start component in HA 0.114.4

### ISSUE THREAD

**Issue by segalion** [alryaz/hass-hekr-component#3]
Seems dont work in HA 0114.4 
 
with this error...

ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hekr: cannot import name 'ConfigType' from 'homeassistant.helpers' ....

**Comment by segalion** [comment]
Same error downgrading to HA 0.113

**Comment by segalion** [comment]
Hei!!!! 
Work fine with HA 0.112.5!!!!

**Comment by alryaz** [comment]
Sorry for taking too long, hotfix will be posted

**Comment by alryaz** [comment]
Posted a hotfix version, v0.2.6
